export type ProductStatus = "completed" | "in-progress";
export type ProductCategory =
  | "sales"
  | "marketing"
  | "agent"
  | "creative"
  | "data";
export type AccessType = "open" | "freemium" | "application" | "sales";
export type ClientType = "web" | "desktop" | "mobile" | "cross";

export interface Product {
  id: string;
  index: number;
  name: string;
  positioning: string;
  url: string;
  access: AccessType;
  client: ClientType;
  owner?: string;
  status: ProductStatus;
  category: ProductCategory;
  note?: string;
  reportPath?: string;
}

export const CATEGORY_LABEL: Record<ProductCategory, string> = {
  sales: "销售",
  marketing: "营销",
  agent: "Agent 协作",
  creative: "创意生成",
  data: "数据分析",
};

export const STATUS_LABEL: Record<ProductStatus, string> = {
  completed: "已完成",
  "in-progress": "进行中",
};

export const ACCESS_LABEL: Record<AccessType, string> = {
  open: "开放",
  freemium: "有免费版",
  application: "申请制",
  sales: "联系销售",
};

// 客户端类型:产品在哪些端可用。
// web 纯网页 / desktop 含桌面客户端(IDE、本地 Agent 等) / mobile 主打手机 / cross 网页+桌面+移动全覆盖
export const CLIENT_LABEL: Record<ClientType, string> = {
  web: "云端",
  desktop: "桌面端",
  mobile: "移动端",
  cross: "全平台",
};

export const products: Product[] = [
  {
    id: "artisan",
    index: 1,
    name: "Artisan AI",
    positioning: "AI 销售员工（AI BDR）",
    url: "https://www.artisan.co/",
    access: "application",
    client: "web",
    owner: "倩倩",
    status: "completed",
    category: "sales",
    reportPath: "artisan-co",
  },
  {
    id: "kuse",
    index: 2,
    name: "Kuse",
    positioning: "AI GTM / AI Sales Automation",
    url: "https://www.kuse.ai/",
    access: "open",
    client: "web",
    owner: "倩倩",
    status: "completed",
    category: "agent",
    reportPath: "kuse-ai",
  },
  {
    id: "junior",
    index: 3,
    name: "Junior AI",
    positioning: "AI 数字员工 / 协作型 Agent",
    url: "https://junior.so/",
    access: "application",
    client: "web",
    status: "completed",
    category: "agent",
    note: "与 Kuse 同公司：Kuse 是系统，Junior 是人格化 AI 员工",
    reportPath: "junior-so",
  },
  {
    id: "okara",
    index: 4,
    name: "Okara AI",
    positioning: "AI Marketing Agent Suite",
    url: "https://okara.ai/",
    access: "open",
    client: "web",
    owner: "倩倩",
    status: "in-progress",
    category: "marketing",
    reportPath: "okara-ai",
  },
  {
    id: "moxt",
    index: 5,
    name: "Moxt",
    positioning: "AI 客户互动 / AI 协作",
    url: "https://moxt.ai/zh-CN",
    access: "freemium",
    client: "web",
    owner: "倩倩",
    status: "completed",
    category: "agent",
    reportPath: "moxt-ai",
  },
  {
    id: "monday",
    index: 6,
    name: "Monday",
    positioning: "企业协作 + AI Workflow 平台",
    url: "https://monday.com/w/agents",
    access: "freemium",
    client: "cross",
    owner: "何龙",
    status: "completed",
    category: "agent",
    reportPath: "monday-agents",
  },
  {
    id: "jasper",
    index: 7,
    name: "Jasper",
    positioning: "AI 营销内容平台",
    url: "https://www.jasper.ai/",
    access: "freemium",
    client: "web",
    owner: "何龙",
    status: "completed",
    category: "marketing",
    reportPath: "jasper-ai",
  },
  {
    id: "pika",
    index: 8,
    name: "Pika Labs",
    positioning: "AI 视频生成",
    url: "https://pika.art/",
    access: "open",
    client: "web",
    owner: "何龙",
    status: "completed",
    category: "creative",
    reportPath: "pika-me",
  },
  {
    id: "relevance",
    index: 9,
    name: "Relevance AI",
    positioning: "通用 Multi-Agent AI 平台",
    url: "https://relevanceai.com/",
    access: "freemium",
    client: "web",
    owner: "何龙",
    status: "completed",
    category: "agent",
    reportPath: "relevanceai-com",
  },
  {
    id: "kaito",
    index: 10,
    name: "Kaito",
    positioning: "Crypto 信息分析平台",
    url: "https://kaito.ai/",
    access: "freemium",
    client: "web",
    owner: "何龙",
    status: "completed",
    category: "data",
    reportPath: "kaito-ai",
  },
  {
    id: "serus",
    index: 11,
    name: "Serus",
    positioning: "AI Agent / 企业自动化",
    url: "https://www.serus.io/",
    access: "sales",
    client: "web",
    owner: "何龙",
    status: "completed",
    category: "agent",
    reportPath: "serus-io",
  },
  {
    id: "11x",
    index: 12,
    name: "11x",
    positioning: "AI 销售员工（AI SDR / AI 电话销售）",
    url: "https://www.11x.ai/",
    access: "sales",
    client: "web",
    owner: "何龙",
    status: "completed",
    category: "sales",
    reportPath: "11x-ai",
  },
  {
    id: "lunar-strategy",
    index: 13,
    name: "Lunar Strategy",
    positioning: "Web3 营销代理公司",
    url: "https://www.lunarstrategy.com/",
    access: "sales",
    client: "web",
    owner: "何龙",
    status: "completed",
    category: "marketing",
    reportPath: "lunarstrategy-com",
  },
  {
    id: "onesight",
    index: 14,
    name: "OneSight",
    positioning: "海外社媒管理工具",
    url: "https://onesight.com/",
    access: "application",
    client: "web",
    owner: "何龙",
    status: "completed",
    category: "marketing",
    reportPath: "onesight-com",
  },
  {
    id: "octok",
    index: 15,
    name: "Octok",
    positioning: "AI 出海团队 / Global Expansion Team Platform",
    url: "https://www.octok.com/",
    access: "application",
    client: "web",
    status: "completed",
    category: "agent",
    note: "6 个具名 AI 角色(Navigator/Alice/Sophia/William/Daniel/Ethan)对应出海公司组织架构",
    reportPath: "octok-com",
  },
  {
    id: "theaicmo",
    index: 16,
    name: "The AI CMO",
    positioning: "AI 营销 Agent / 自主跑 Campaign",
    url: "https://theaicmo.com/",
    access: "open",
    client: "web",
    status: "completed",
    category: "marketing",
    note: "plans strategy → writes assets → publishes → learns,定位 agent 而非 prompt 工具",
    reportPath: "theaicmo-com",
  },
  {
    id: "kore",
    index: 17,
    name: "Kore.ai",
    positioning: "企业级 Agentic AI 平台（客服 + 员工提效）",
    url: "https://www.kore.ai/",
    access: "sales",
    client: "web",
    status: "completed",
    category: "agent",
    reportPath: "kore-ai",
  },
  {
    id: "pylon",
    index: 18,
    name: "Pylon",
    positioning: "AI 原生 B2B 客户支持平台",
    url: "https://www.usepylon.com/",
    access: "freemium",
    client: "web",
    status: "completed",
    category: "agent",
    reportPath: "usepylon-com",
  },
  {
    id: "dust",
    index: 19,
    name: "Dust",
    positioning: "企业多 Agent 协作平台（按岗位命名、可接力）",
    url: "https://dust.tt/",
    access: "freemium",
    client: "web",
    status: "completed",
    category: "agent",
    note: "Web 端为主,另有浏览器扩展",
    reportPath: "dust-tt",
  },
  {
    id: "fin",
    index: 20,
    name: "Fin",
    positioning: "AI 客服 Agent（端到端处理工单，Intercom 旗下）",
    url: "https://fin.ai/",
    access: "freemium",
    client: "web",
    status: "completed",
    category: "agent",
    reportPath: "fin-ai",
  },
  {
    id: "marvis",
    index: 21,
    name: "马维斯 Marvis",
    positioning: "执行型 AI 助手（24h 在线、会动手干活）",
    url: "https://marvis.qq.com/",
    access: "application",
    client: "cross",
    status: "completed",
    category: "agent",
    note: "腾讯系，内测中；Windows / macOS / Android / iOS 四端",
    reportPath: "marvis-qq-com",
  },
  {
    id: "codebuddy",
    index: 22,
    name: "CodeBuddy",
    positioning: "AI 编程 Agent（自主规划执行、交付可验收成果）",
    url: "https://www.codebuddy.cn/work/",
    access: "freemium",
    client: "desktop",
    status: "completed",
    category: "agent",
    note: "腾讯系；VS Code / JetBrains 插件 + 命令行",
    reportPath: "codebuddy-cn",
  },
  {
    id: "qclaw",
    index: 23,
    name: "QClaw",
    positioning: "通用桌面自动化 Agent（微信指令驱动本地电脑）",
    url: "https://qclaw.qq.com/",
    access: "application",
    client: "desktop",
    status: "completed",
    category: "agent",
    note: "腾讯系，内测中；对标开源项目 OpenClaw 的零门槛简化版",
    reportPath: "qclaw-qq-com",
  },
  {
    id: "dumate",
    index: 24,
    name: "Dumate",
    positioning: "执行型 AI 智能体（把事做完并交付结果）",
    url: "https://www.dumate.cn/app",
    access: "freemium",
    client: "desktop",
    status: "completed",
    category: "agent",
    note: "需下载客户端,直接读写本地文件",
    reportPath: "dumate-cn",
  },
  {
    id: "helio",
    index: 25,
    name: "Helio",
    positioning: "AI 原生协作工作台（人与 AI 同事共用频道、工单与状态）",
    url: "https://www.helio.im/",
    access: "application",
    client: "desktop",
    status: "completed",
    category: "agent",
    note: "Web 端 + macOS / Windows 桌面客户端,从工程研发与事故响应场景切入",
    reportPath: "helio-im",
  },
  {
    id: "omniwork",
    index: 26,
    name: "OmniWork",
    positioning: "面向创意工作的 Agent OS（一句目标自动跑到成品）",
    url: "https://www.omniwork.ai/",
    access: "application",
    client: "web",
    status: "completed",
    category: "creative",
    note: "专家市场 + Omni 编排器，目前仅深入演示社媒涨粉一个场景，邀请码门控",
    reportPath: "omniwork-ai",
  },
];

export const stats = {
  total: products.length,
  completed: products.filter((p) => p.status === "completed").length,
  inProgress: products.filter((p) => p.status === "in-progress").length,
};
